export const ROUTER__LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export const APPLICATION__TOGGLE_SIDEMENU = 'APPLICATION__TOGGLE_SIDEMENU';
export const APPLICATION__CLOSE_SIDELISTS = 'APPLICATION__CLOSE_SIDELISTS';
export const APPLICATION__TOGGLE_PLAYLIST = 'APPLICATION__TOGGLE_PLAYLIST';

export const ARTISTS__FETCH_LIST = 'ARTISTS__FETCH_LIST';
export const ARTISTS__LIST_FETCH_FAILED = 'ARTISTS__LIST_FETCH_FAILED';
export const ARTISTS__UPDATE_LIST = 'ARTISTS__UPDATE_LIST';
export const ARTISTS__FETCH_ARTIST = 'ARTISTS__UPDATE_LIST';
export const ARTISTS__SET_SHOWING_ARTIST = 'ARTISTS__SET_SHOWING_ARTIST';
export const ARTISTS__ARTIST_FETCH_FAILED = 'ARTISTS__ARTIST_FETCH_FAILED';

export const ALBUMS__FETCH_LIST = 'ALBUMS__FETCH_LIST';
export const ALBUMS__UPDATE_LIST = 'ALBUMS__UPDATE_LIST';
export const ALBUMS__LIST_FETCH_FAILED = 'ALBUMS__LIST_FETCH_FAILED';

export const ALBUMS__FETCH_ALBUM = 'ALBUMS__FETCH_ALBUM';
export const ALBUMS__SET_SHOWING_ALBUM = 'ALBUMS__SET_SHOWING_ALBUM';
export const ALBUMS__ALBUM_FETCH_FAILED = 'ALBUMS__ALBUM_FETCH_FAILED';
