export const ROUTER__LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export const APPLICATION__TOGGLE_SIDEMENU = 'APPLICATION__TOGGLE_SIDEMENU';

export const ARTIST_LIST__FETCH = 'ARTIST_LIST__FETCH';
export const ARTIST_LIST__FETCH_FAILED = 'ARTIST_LIST__FETCH_FAILED';
export const ARTIST_LIST__FETCH_SUCESSFUL = 'ARTIST_LIST__FETCH_SUCESSFUL';

export const ALBUMS__FETCH_LIST = 'ALBUMS__FETCH_LIST';
export const ALBUMS__UPDATE_LIST = 'ALBUMS__UPDATE_LIST';
export const ALBUMS__LIST_FETCH_FAILED = 'ALBUMS__LIST_FETCH_FAILED';

export const ALBUMS__FETCH_ALBUM = 'ALBUMS__FETCH_ALBUM';
export const ALBUMS__SET_SHOWING_ALBUM = 'ALBUMS__SET_SHOWING_ALBUM';
export const ALBUMS__ALBUM_FETCH_FAILED = 'ALBUMS__ALBUM_FETCH_FAILED';
