export const ARTIST_LIST__FETCH = 'ARTIST_LIST__FETCH';
export const ARTIST_LIST__FETCH_FAILED = 'ARTIST_LIST__FETCH_FAILED';
export const ARTIST_LIST__FETCH_SUCESSFUL = 'ARTIST_LIST__FETCH_SUCESSFUL';
export const APPLICATION__TOGGLE_SIDEMENU = 'APPLICATION__TOGGLE_SIDEMENU';
